version: "2"

services:
    elasticsearch1:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
        container_name: elasticsearch1
        environment:
            - cluster.name=${CLUSTER_NAME}
            - node.name=elasticsearch1
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=true
            - xpack.security.authc.realms.native1.type=native
            - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
            - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
        ports:
            - "19200:9200"

    elasticsearch2:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
        container_name: elasticsearch2
        environment:
            - cluster.name=${CLUSTER_NAME}
            - node.name=elasticsearch2
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=true
            - xpack.security.authc.realms.native1.type=native
            - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
            - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
        ports:
            - "29200:9200"

    elasticsearch3:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
        container_name: elasticsearch3
        environment:
            - cluster.name=${CLUSTER_NAME}
            - node.name=elasticsearch3
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=true
            - xpack.security.authc.realms.native1.type=native
            - discovery.seed_hosts=elasticsearch1,elasticsearch2,elasticsearch3
            - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
        ports:
            - "39200:9200"

    monitor:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
        container_name: monitor
        environment:
            - cluster.name=docker-monitor-cluster
            - node.name=monitor
            - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=true
            - discovery.seed_hosts=monitor
            - cluster.initial_master_nodes=monitor
        ports:
            - "9200:9200"

    kibana-devtools:
        image: docker.elastic.co/kibana/kibana:7.17.5
        container_name: kibana-devtools
        environment:
            SERVERNAME: kibana-devtools
            ELASTICSEARCH_HOSTS: http://elasticsearch3:9200
            ELASTICSEARCH_USERNAME: elastic
            ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
        ports:
            - "15601:5601"

    kibana-dashboard:
        image: docker.elastic.co/kibana/kibana:7.17.5
        container_name: kibana-dashboard
        environment:
            SERVERNAME: kibana-dashboard
            ELASTICSEARCH_HOSTS: http://monitor:9200
            ELASTICSEARCH_USERNAME: elastic
            ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
        ports:
            - "${KIBANA_PORT}:5601"
